### ISSUE TITLE
Internal pages not listet

### ISSUE THREAD

**Issue by Patta** [jokumer/direct_mail#11]
Internal pages in the selected SysFolder are not listet/shown in the direct mail wizard.

TYPO3 9.5.13
PHP 7.3.13
Composer mode
Branch TYPO3_9

**Comment by jokumer** [comment]
Accepted. It is reproduceable with classic mode (none composer) and PHP 7.2
Thx for reporting.

**Comment by jokumer** [comment]
There was a default configuration `$GLOBALS['TYPO3_CONF_VARS']['FE']['content_doktypes']` which has been removed in TYPO3 v9. The install/updater also removes this configuration silently from local configuration.
In direct_mail this configuration is used to filter pages, which may contain content and can be send as newsletter.
DB request for Internal pages now considers doktype constraints, if they still exists.
