### ISSUE TITLE
Draft mail recipients are not updated with new users

### ISSUE THREAD

**Issue by Patta** [jokumer/direct_mail#12]
If a mail is created from a draft via the scheduler, new users are not in the recipient list and the mail are not delivered to them.

Until this bug is not solved, sent mails from drafts is useless.

The bug exists for a very long time and should be fixed in version 6.0. Many thanks in advance!

Related issues:
https://forge.typo3.org/issues/34432
https://github.com/kartolo/direct_mail/issues/115

**Comment by jokumer** [comment]
Patch added from https://forge.typo3.org/issues/34432.
Thx for the hint.
