### ISSUE TITLE
createDirectMailRecordFromPage->pageRecordOverlay

### ISSUE THREAD

**Issue by bernd-reindl** [jokumer/direct_mail#15]
The condition if (is_array($pageRecordOverlay)) is always false, because fetchColumn(0) is used to fetch the title. fetchColumn(0) returns the first column of the next row as (in this case) string.

So the condition has to be if ($pageRecordOverlay) or if (is_string($pageRecordOverlay)) and the assignment has to be $pageRecord['title'] = $pageRecordOverlay; (not $pageRecord['title'] = $pageRecordOverlay['title'];)

**Comment by jokumer** [comment]
Good catched. Please help me, to reproduce a case to se if it fails currently or succeed with your suggestion. Or even better create a pull request, if you want.

**Comment by bernd-reindl** [comment]
you have to set up a TYPO3 9.5.x installation with 2 languages (e.g. default - DE; L1: EN) and have set up the sites like in the screenshots.

Then you create a new page with contents in both languages.

Now you create a new newsletter from the localized language (EN) and check the content of $pageRecordOverlay in pageRecordOverlay().

Screenshots:
![sites1](https://user-images.githubusercontent.com/2369089/72872269-3a39be80-3ced-11ea-802c-97d73dcc2912.jpg)
![sites2-1](https://user-images.githubusercontent.com/2369089/72872279-3d34af00-3ced-11ea-840f-46b29dc4abc7.jpg)
![sites2-2](https://user-images.githubusercontent.com/2369089/72872285-3efe7280-3ced-11ea-9b90-b7be9a830566.jpg)

**Comment by jokumer** [comment]
Thanks for your report. It was hard to find the little flag icon-buttons, where to click in any of the direct_mail modules to reproduce your use case.
