### ISSUE TITLE
Redundant parameter in jumpurl link

### ISSUE THREAD

**Issue by thernst** [jokumer/direct_mail#17]
The fix for issue #16 generates correct base urls for the links in the email. With jumpurl enabled, these links get extended by several parameters. As the base url is now the direct url of the newsletter page, adding an additional "id" parameter for the jumpurl links is not necessary.

Class DirectMailUtility can be changed in method "fetchUrlContentsForDirectMailRecord"  from
https://github.com/jokumer/direct_mail/blob/d596500d8a16a2af695a68a7f7d4f9dfcd6729b1/Classes/DirectMailUtility.php#L1314-L1319

to

```
            $htmlmail->jumperURL_prefix = $urlBase .
                '?mid=###SYS_MAIL_ID###' .
                (intval($params['jumpurl_tracking_privacy']) ? '' : '&rid=###SYS_TABLE_NAME###_###USER_uid###') .
                '&aC=###SYS_AUTHCODE###' .
                '&jumpurl=';
```

**Comment by jokumer** [comment]
Thank you @thernst for checking direct_mail within jumpurl.
