### ISSUE TITLE
jumpurl processing for email links

### ISSUE THREAD

**Issue by thernst** [jokumer/direct_mail#18]
If `jumperURL_useId` is off, the jumpUrl target is added as links to the newsletter base address. This works for http:// and https:// links. For mailto: links, jumpurl processing fails as the JumpurlController does not add the juHash in this case.

To fix this, the following lines should be inserted after
https://github.com/jokumer/direct_mail/blob/d596500d8a16a2af695a68a7f7d4f9dfcd6729b1/Classes/Hooks/JumpurlController.php#L160-L164

```
                } elseif (GeneralUtility::validEmail(substr($jumpurl,7)) && preg_match('#^(mailto:)#', $jumpurl)) {
                    // Also allow jumpurl to be a valid mailto link
                    GeneralUtility::_GETset(GeneralUtility::hmac($jumpurl, 'jumpurl'), 'juHash');
                    $responseType = -1;
                }
```

**Comment by jokumer** [comment]
Thank you @thernst for your investigation. Your description of the issues together with your suggestion to solve it, really helps, to keep this extension running with current TYPO3 versions.

Are you able to request such a change via PullRequest next time with Github, or want to learn how to? https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by jokumer** [comment]
@thernst your change was removed within the latest security fix, which I merged into current TYPO3_9 branch. I did try to reproduce the issue, you describe - no issues found.
A workaround, if it should appear again could be, to check:

- direct_mail configuration disable "Enable jump URL's for mailto links" (enable_mailto_jump_url)
- TypoScript setup 'config.jumpurl_mailto_disable = 1'

**Comment by thernst** [comment]
@jokummer Thank you for integrating the latest security fixes into this branch. I will perform some tests with the latest version of this branch during the next days and keep you updated.

**Comment by thernst** [comment]
Up to now I did not encounter this issue again.
