### ISSUE TITLE
Speaking URL too long for sys_dmail:long_link_rdct_url

### ISSUE THREAD

**Issue by prathers** [jokumer/direct_mail#19]
When creating newsletter, I get an error `Data too long for column 'long_link_rdct_url'`.

The field is a VARCHAR(80)

Raising it to 255 solved the problem. I guess it's caused by TYPO3 routing

**Comment by jokumer** [comment]
This field should then have varchar(2048), like defined for path segments or canonical urls in TYPO3 system extensions.
Would you qreate a pull request?
