### ISSUE TITLE
Display recipient lists broken

### ISSUE THREAD

**Issue by thernst** [jokumer/direct_mail#22]
When using TYPO3_9 branch with the latest security updates, showing the recipent lists causes an error.

The reason is that DirectMailUtility::getSpecialQueryIdList tries to do DB selection via $GLOBALS['TYPO3_DB'].

Usage of $GLOBALS['TYPO3_DB'] was introduced with commit d735416 ("Adopt commit 'e675de9' into TYPO3_9")

Original version from commit e675de9 ("[Security] respect user restriction on query generator") is working in Typo3 V9 context.

I suggest to revert d735416

**Comment by jokumer** [comment]
What kind of recipients do you have configured, to reproduce the issue?
- From page
- Plain list
- Static list
- Special query
- From other recipient lists

And when the error occurse? When opening Module for recipient lists or a within a single recipient list?

**Comment by thernst** [comment]
I have "special query" recipient lists. The issue occurs directly when opening the recipient list module.

**Comment by jokumer** [comment]
I have a lot of special queries, with no issue. Kan you send data from this sys_dmail_group field query, which produces this error?

**Comment by jokumer** [comment]
Oh, sorry, my fault. I had installed exte db_legacy, which solves such db queries.
Now I can reproduce the error.

**Comment by jokumer** [comment]
I reverted this change. It includes a breaking in expected amount of recipients to send to, when editors with reduced access to storage pages in page tree, where recipients may be located.
Thx for your hint.

@thernst Would still you test mailto behavior?

**Comment by thernst** [comment]
Thank you for fixing this quickly. I will do a complete test of direct_mail in our environment and let you know the results.
