### ISSUE TITLE
Testmail given an error

### ISSUE THREAD

**Issue by chrcan** [jokumer/direct_mail#5]
(1/1) Swift_RfcComplianceException
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

**Comment by villamarianne** [comment]
Did you set the Sender email in Configuration?

Als the answer for #7

**Comment by chrcan** [comment]
@villamarianne yes but when i comment in swiftmailer -> Mailbox Header.php thi lines the error is gon but no mail comming...
private function _assertValidAddress($address)
    {
        if (!preg_match('/^'.$this->getGrammar()->getDefinition('addr-spec').'$/D',
            $address)) {
            //throw new Swift_RfcComplianceException(
            //    'Address in mailbox given ['.$address.
            //    '] does not comply with RFC 2822, 3.6.2.'
            //    );
        }
    }

**Comment by villamarianne** [comment]
With this comments you are just surpressing the error message, the error still occurs.

`['.$address.']` becomes `[]` wich means, there must be an empty email-adress somewhere. Either in one of the recepients or in sender email configuration.

**Comment by chrcan** [comment]
ok that means no e-mail address will be given by direct-mail

**Comment by jokumer** [comment]
I can not reproduce your issue, as you described here. Could you describe, your setup and how you send a "testmail", which gives an error?

**Comment by jokumer** [comment]
@chrcan Such error is thrown by switfmailer, a thirdparty package as used in TYPO3 for sending emails.
It occurs if one single recipient email address is invalid.
Check your emails if they comply RFC 2822 standards for Internet Message Format.

Otherwise I will close this issue the next days due to lack of feedback.
