### ISSUE TITLE
cvs import

### ISSUE THREAD

**Issue by chrcan** [jokumer/direct_mail#6]
cvs import in recipient list given an error
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: strpos() expects parameter 3 to be integer, string given in /var/www/vhosts/midomain.at/httpdocs/Typo9/Source/Extensions/direct-mail/Classes/Importer.php line 928

**Comment by jokumer** [comment]
Thx for reporting
