### ISSUE TITLE
Backend Module ArgumentCountError

### ISSUE THREAD

**Issue by Patta** [jokumer/direct_mail#9]
Branch: TYPO3_9
Composer mode
TYPO3 9.5.11

(1/1) ArgumentCountError
Too few arguments to function DirectMailTeam\DirectMail\Module\Statistics::mainAction(), 1 passed and exactly 2 expected

in ...\packages\direct_mail\Classes\Module\Statistics.php line 170
```
     * @param ResponseInterface $response The reponse object sent to the backend
     *
     * @return ResponseInterface Return the response object
     */
    public function mainAction(ServerRequestInterface $request, ResponseInterface $response)
    {
        $this->getLanguageService()->includeLLFile('EXT:direct_mail/Resources/Private/Language/locallang_mod2-6.xlf');
        $this->getLanguageService()->includeLLFile('EXT:direct_mail/Resources/Private/Language/locallang_csh_sysdmail.xlf');
```
at DirectMailTeam\DirectMail\Module\Statistics->mainAction(object(TYPO3\CMS\Core\Http\ServerRequest))
at call_user_func_array(array(object(DirectMailTeam\DirectMail\Module\Statistics), 'mainAction'), array(object(TYPO3\CMS\Core\Http\ServerRequest)))

**Comment by jokumer** [comment]
@Patta I can not reproduce your issue (TYPO3 v9.5.13).
When and where does this error occur in your installation?
I tried to open Backend module "Direct Mail" > "Statistic" without any error.

**Comment by Patta** [comment]
@jokumer The error occurs in every directmail backend module. When entering the module.

TYPO3 9.5.13
PHP 7.3.13
Linux and/or Windows

**Comment by jokumer** [comment]
@Patta Sorry, then we need to dig deeper into your issue. We need to find out, why only TYPO3\CMS\Core\Http\ServerRequest is passed as argument, and second argument for response is missing. Do you have any third party extension or configuration, which manipulates request and response?

Her is my working test environment, including direct_mail from my github account and the introduction package.

composer.json
```
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://composer.typo3.org/"
        },
        {
            "type": "git",
            "url": "https://github.com/jokumer/direct_mail"
        }
    ],
    "name": "typo3/cms-base-distribution",
    "description": "TYPO3 CMS Base Distribution",
    "license": "GPL-2.0-or-later",
    "config": {
        "platform": {
            "php": "7.2"
        }
    },
    "require": {
        "helhum/typo3-console": "^5.5.5",
        "typo3/minimal": "^9.5",
        "typo3/cms-about": "^9.5",
        "typo3/cms-adminpanel": "^9.5",
        "typo3/cms-belog": "^9.5",
        "typo3/cms-beuser": "^9.5",
        "typo3/cms-felogin": "^9.5",
        "typo3/cms-fluid-styled-content": "^9.5",
        "typo3/cms-form": "^9.5",
        "typo3/cms-impexp": "^9.5",
        "typo3/cms-info": "^9.5",
        "typo3/cms-redirects": "^9.5",
        "typo3/cms-reports": "^9.5",
        "typo3/cms-rte-ckeditor": "^9.5",
        "typo3/cms-setup": "^9.5",
        "typo3/cms-seo": "^9.5",
        "typo3/cms-sys-note": "^9.5",
        "typo3/cms-t3editor": "^9.5",
        "typo3/cms-tstemplate": "^9.5",
        "typo3/cms-viewpage": "^9.5",
        "typo3/cms-introduction": "4.0.1",
        "directmailteam/direct-mail": "dev-TYPO3_9"
    },
    "scripts": {
        "typo3-cms-scripts": [
            "typo3cms install:fixfolderstructure",
            "typo3cms install:generatepackagestates"
        ],
        "post-autoload-dump": [
            "@typo3-cms-scripts"
        ]
    }
}
```

TYPO3 9.5.13 (classic and composer mode)
PHP 7.2.18 and 7.3.0
Mac OS

**Comment by Patta** [comment]
I use a lot of extensions yes, but do not exactly know which manipulates the response in the backend.
Same argument error with windows and linux.

**Comment by Patta** [comment]
I have found the problem, the system feature in 9.5 "simplifiedControllerActionDispatching" must be deactivated.

Basicly exactly the same issue as described here: https://github.com/xperseguers/t3ext-image_autoresize/issues/21
Solution here: https://github.com/xperseguers/t3ext-image_autoresize/commit/8de509ed85b8a174f645e971875cc457a7dde1f0

**Comment by jokumer** [comment]
Good cached @Patta Thx. I will have a look later on it. Or would you try to patch it an make a pull request here?

**Comment by Patta** [comment]
I would likely fail, please patch it ;)

**Comment by jokumer** [comment]
No problem ;)
